server:
  port: 8080
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${db_hostname}:${db_port}/${db_database}?createDatabaseIfNotExist=true
    username: ${db_user}
    password: ${db_password}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false
  sql:
    init:
      mode: never
  web:
    resources:
      static-locations:
        - classpath:/public/
